services:
  router:
    volumes:
      - ./templates:/etc/nginx/templates:ro
    build: .
    environment:
      SERVER0: server0:${NGINX_PORT}
      SERVER1: server1:${NGINX_PORT}
      SERVER2: server2:${NGINX_PORT}
      NGINX_RESOLVER: 127.0.0.11
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"

  server0:
    build: 
      context: ./test_image
      args:
        FILE: ${FILE0}
  server1:
    build: 
      context: ./test_image
      args:
        FILE: ${FILE1}
  server2:
    build: 
      context: ./test_image
      args:
        FILE: ${FILE2}
