FROM nginx:alpine
RUN rm /usr/share/nginx/html/index.html
COPY ./public /usr/share/nginx/html/
COPY ./templates /etc/nginx/templates/
ARG NGINX_PORT=8000
ARG NGINX_RESOLVER=8.8.8.8
ARG SERVER0
ARG SERVER1
ARG SERVER2

ENV NGINX_PORT=${NGINX_PORT}
ENV NGINX_RESOLVER=${NGINX_RESOLVER}
ENV SERVER0=${SERVER0}
ENV SERVER1=${SERVER1}
ENV SERVER2=${SERVER2}
