name: Test
on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Docker Image and Run Tests
    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: make
